"""The hitting plan: tendency tables turned into sentences a hitter can use.

Everything else in this project measures. This module writes the part of an
advance report a player actually reads before he walks to the plate: a few
short lines, split by which side of the plate he hits from, saying what to look
for and what to lay off.

The people who build these reports describe the job the same way. One front
office described taking "a phone book's amount of information" and paring it
to a few pages plus one-sentence notes for in-game use; another warned that the
staff's job is to separate what is usable from what is cosmetic. So the rules
here are deliberately few, each one gated on sample size, and each sentence
carries the number of pitches behind it.

Two constraints shape the wording.

The plan is built from how OFTEN he does things, not from what they cost him in
runs. Run-value estimates do not resolve at one season of one pitcher (see
`flags.benjamini_hochberg`), while usage rates on several hundred pitches do.
A plan built on frequency is what advance scouting has always been; claiming
the run cost would be claiming precision the data does not have.

It is written from the HITTER's point of view, because the hitter is the
reader. A count where the pitcher is behind is "when you're ahead in the
count", and the tendency tables are flipped accordingly here, not in the
reader's head.

Nothing here is generated by a language model. Every sentence comes from a
rule with a threshold, so the same data always produces the same plan and any
line can be traced to the rows that produced it.
"""

from __future__ import annotations

import pandas as pd

from src import config
from src.metrics import counts, location, splits

# What hitters and coaches call each pitch. "Four-seam" rather than "fastball"
# for FF, because a pitcher with a sinker has two fastballs and "sit fastball"
# would not say which.
COACH_NAMES: dict[str, str] = {
    "FF": "four-seam",
    "SI": "sinker",
    "FC": "cutter",
    "FS": "splitter",
    "CH": "changeup",
    "SC": "screwball",
    "FO": "forkball",
    "CU": "curveball",
    "KC": "knuckle-curve",
    "SL": "slider",
    "ST": "sweeper",
    "SV": "slurve",
    "KN": "knuckleball",
}

# Hard, breaking, offspeed — the three buckets a hitter actually sits on. "Sit
# hard" is a plan; "sit four-seam 34%, sinker 19%, cutter 18%" is a table.
PITCH_FAMILY: dict[str, str] = {
    "FF": "hard", "SI": "hard", "FC": "hard",
    "CU": "breaking", "KC": "breaking", "SL": "breaking",
    "ST": "breaking", "SV": "breaking",
    "FS": "offspeed", "CH": "offspeed", "SC": "offspeed", "FO": "offspeed",
}

SIDE_NAMES: dict[str, str] = {"L": "lefties", "R": "righties"}


def name(pitch_type: str) -> str:
    """A pitch code as a coach would say it."""
    return COACH_NAMES.get(pitch_type, pitch_type.lower())


def _pct(value: float) -> str:
    return f"{value:.0%}"


def _key(label: str, text: str, n: int) -> dict:
    return {"label": label, "text": text, "n": int(n)}


def _top(usage: pd.DataFrame, situation: str, side: str) -> pd.DataFrame:
    rows = usage[(usage["situation"] == situation) & (usage["stand"] == side)]
    return rows.sort_values("share", ascending=False)


def _list_pitches(rows: pd.DataFrame, limit: int = 3) -> str:
    return ", ".join(
        f"{name(r.pitch_type)} {_pct(r.share)}" for r in rows.head(limit).itertuples()
    )


# ---------------------------------------------------------------------------
# Per-side keys
# ---------------------------------------------------------------------------


def _cut(key: str, default: float) -> float:
    """A plan cutoff from config.yaml's `plan` section.

    Every threshold that decides which sentence a hitter reads lives in config,
    not here, so the calibration run across many pitchers can move them without
    touching the wording.
    """
    return float(config.get(f"plan.{key}", default))


# ---------------------------------------------------------------------------
# Measurements behind each per-side rule
#
# Each returns the numbers a rule reads, or None when the sample is below its
# gate. They are separate from the sentence-writing functions below so that a
# calibration run can record the numbers for every pitcher — including the
# ones where the rule stays silent, which are exactly the cases needed to see
# whether a cutoff is in the right place.
# ---------------------------------------------------------------------------


def first_pitch_numbers(frame: pd.DataFrame, usage: pd.DataFrame, side: str) -> dict | None:
    """First-pitch mix to this side, and how often TAKEN first pitches are strikes."""
    min_n = int(config.get("flags.min_n.first_pitch", 30))
    rows = _top(usage, "first_pitch", side)
    if len(rows) == 0 or int(rows.iloc[0]["situation_n"]) < min_n:
        return None

    side_frame = frame[(frame["stand"] == side)
                       & (frame["balls"] == 0) & (frame["strikes"] == 0)]
    taken = side_frame[~side_frame["is_swing"].eq(True)]
    called = (
        float(taken["is_called_strike"].eq(True).mean())
        if len(taken) >= min_n else float("nan")
    )
    lead = rows.iloc[0]
    second = rows.iloc[1] if len(rows) > 1 else None
    return {
        "n": int(lead["situation_n"]),
        "top": lead.pitch_type,
        "top_share": float(lead.share),
        "second": second.pitch_type if second is not None else None,
        "second_share": float(second.share) if second is not None else float("nan"),
        "takes": int(len(taken)),
        "called_on_takes": called,
    }


def hitters_count_numbers(usage: pd.DataFrame, side: str) -> dict | None:
    """The mix when the hitter is ahead: hard-family share and the top pitch."""
    min_n = int(config.get("flags.min_n.predictable_count", 20)) + 10
    rows = _top(usage, "pitcher_behind", side)
    if len(rows) == 0 or int(rows.iloc[0]["situation_n"]) < min_n:
        return None

    families = rows.assign(
        family=rows["pitch_type"].map(PITCH_FAMILY).fillna("other")
    ).groupby("family")["share"].sum()
    lead = rows.iloc[0]
    return {
        "n": int(lead["situation_n"]),
        "hard_share": float(families.get("hard", 0.0)),
        "top": lead.pitch_type,
        "top_share": float(lead.share),
        "rows": rows,
    }


def two_strike_numbers(frame: pd.DataFrame, usage: pd.DataFrame, side: str) -> dict | None:
    """His two-strike pitch to this side, its miss rate, and how often it ends low."""
    min_n = int(config.get("flags.min_n.first_pitch", 30))
    rows = _top(usage, "two_strikes", side)
    if len(rows) == 0 or int(rows.iloc[0]["situation_n"]) < min_n:
        return None

    lead = rows.iloc[0]
    pitches = frame[(frame["stand"] == side) & (frame["strikes"] == 2)
                    & (frame["pitch_type"] == lead.pitch_type)]
    swings = int(pitches["is_swing"].eq(True).sum())
    whiffs = int(pitches["is_whiff"].eq(True).sum())
    located = pitches.dropna(subset=["plate_z", "sz_bot"])
    return {
        "n": int(lead["situation_n"]),
        "top": lead.pitch_type,
        "top_share": float(lead.share),
        "swings": swings,
        "whiff": whiffs / swings if swings else float("nan"),
        "below": (
            float((located["plate_z"] < located["sz_bot"]).mean())
            if len(located) else float("nan")
        ),
    }


def rare_pitches(frame: pd.DataFrame, side: str, max_share: float | None = None) -> dict | None:
    """Arsenal pitches this side sees less than `max_share` of the time."""
    if max_share is None:
        max_share = _cut("rare_share", 0.03)
    working = counts.restrict_to_arsenal(frame)
    side_frame = working[working["stand"] == side]
    if len(side_frame) < 100:
        return None

    shares = side_frame["pitch_type"].value_counts(normalize=True)
    arsenal = list(working["pitch_type"].value_counts().index)
    return {
        "n": int(len(side_frame)),
        "arsenal_size": len(arsenal),
        "rare": [(p, float(shares.get(p, 0.0))) for p in arsenal
                 if shares.get(p, 0.0) < max_share],
        # How close this side comes to the cutoff, recorded even when nothing
        # is rare, so a calibration run can see where the line sits.
        "min_share": min(float(shares.get(p, 0.0)) for p in arsenal),
    }


# ---------------------------------------------------------------------------
# Per-side keys: the sentences
# ---------------------------------------------------------------------------


def first_pitch_key(frame: pd.DataFrame, usage: pd.DataFrame, side: str) -> dict | None:
    """How he starts hitters on this side, and whether to take or swing.

    The take-or-swing advice is based on what happens when the first pitch is
    TAKEN — how often it is called a strike — because that is the only number
    that answers the hitter's actual question: "if I take this, where does the
    count go?"

    The obvious number is wrong for this. The usual first-pitch strike rate
    counts any pitch that is swung at as a strike, so it is inflated by every
    other hitter who swung. Yamamoto's is 63%, which reads as "taking puts you
    down 0-1"; but when hitters actually take his first pitch it is called a
    strike only 45% of the time. The first version of this rule used the
    inflated number and gave the opposite advice.
    """
    m = first_pitch_numbers(frame, usage, side)
    if m is None:
        return None

    # The label already says "First pitch", so the sentence starts with the
    # pitch rather than repeating it.
    text = f"{name(m['top']).capitalize()} {_pct(m['top_share'])}"
    if m["second"] and m["second_share"] >= 0.10:
        text += f", then {name(m['second'])} {_pct(m['second_share'])}"
    text += "."

    called = m["called_on_takes"]
    if called == called:
        if called >= _cut("first_pitch_swing_above", 0.55):
            text += (f" Taken first pitches are called strikes {_pct(called)} of "
                     f"the time, so taking usually puts you down 0-1 — be ready to "
                     f"swing at a strike.")
        elif called <= _cut("first_pitch_take_below", 0.45):
            text += (f" Taken first pitches are called strikes only {_pct(called)} "
                     f"of the time — you can make him throw one.")
        else:
            text += (f" Taken first pitches are called strikes {_pct(called)} of "
                     f"the time — no strong case for taking or swinging.")

    return _key("First pitch", text, m["n"])


def hitters_count_key(usage: pd.DataFrame, side: str) -> dict | None:
    """What to sit on when the hitter is ahead in the count.

    "Sit hard" when the hard family takes most of the count, because that is
    how a hitter thinks about it: he cannot sit on four-seam AND sinker AND
    cutter separately, but he can be on time for velocity.
    """
    m = hitters_count_numbers(usage, side)
    if m is None:
        return None
    rows = m["rows"]

    if m["hard_share"] >= _cut("sit_hard_share", 0.60):
        # A pitch he throws 0% of the time in this count is not part of the
        # instruction, even if it belongs to the family.
        hard_rows = rows[(rows["pitch_type"].map(PITCH_FAMILY) == "hard")
                         & (rows["share"] >= 0.03)]
        text = (f"Sit hard — he goes to a fastball {_pct(m['hard_share'])} of the "
                f"time ({_list_pitches(hard_rows)}).")
    elif m["top_share"] >= _cut("sit_pitch_share", 0.40):
        text = f"Sit {name(m['top'])} — {_pct(m['top_share'])} of the time."
    else:
        text = (f"He still mixes ({_list_pitches(rows)}), so look for a zone, "
                f"not a pitch.")

    return _key("Ahead in the count", text, m["n"])


def two_strike_key(frame: pd.DataFrame, usage: pd.DataFrame, side: str) -> dict | None:
    """His put-away pitch to this side, how often it misses bats, and where.

    The location clause is what turns a fact into an instruction. "He throws
    the splitter with two strikes" tells a hitter what is coming; "and most of
    them finish below the zone" tells him to lay off it.
    """
    m = two_strike_numbers(frame, usage, side)
    if m is None:
        return None

    low = m["below"] == m["below"] and m["below"] >= _cut("lay_off_low_share", 0.50)
    text = f"Expect the {name(m['top'])} ({_pct(m['top_share'])})."
    if m["whiff"] == m["whiff"] and m["swings"] >= _cut("min_two_strike_swings", 20):
        text += f" It misses bats on {_pct(m['whiff'])} of swings"
        text += (f", and {_pct(m['below'])} of them finish below the zone — "
                 f"lay off it low.") if low else "."
    elif low:
        text += f" {_pct(m['below'])} of them finish below the zone — lay off it low."

    return _key("Two strikes", text, m["n"])


def wont_show_key(frame: pd.DataFrame, side: str, max_share: float | None = None) -> dict | None:
    """Pitches he essentially never throws to this side.

    The single most useful line for shrinking a hitter's problem: a pitcher who
    never shows lefties his slider is a smaller arsenal to a lefty, and the
    hitter can stop thinking about it.
    """
    m = rare_pitches(frame, side, max_share)
    if m is None or not m["rare"]:
        return None

    remaining = m["arsenal_size"] - len(m["rare"])
    rare_text = " or the ".join(name(p) for p, _ in m["rare"])
    detail = ", ".join(f"{name(p)} {_pct(share)}" for p, share in m["rare"])
    words = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six"}
    text = (f"He basically won't show you the {rare_text} ({detail}). "
            f"Treat him as a {words.get(remaining, remaining)}-pitch pitcher.")
    return _key("Won't see", text, m["n"])


# ---------------------------------------------------------------------------
# Keys that apply to both sides
# ---------------------------------------------------------------------------


def recent_change_key(frame: pd.DataFrame, last_n: int = 5) -> dict | None:
    """What has changed in his most recent outings.

    Only shifts the recent-form test marks notable are mentioned, and a
    velocity change only if it is at least half a mile per hour, so this line
    stays empty for a pitcher who is simply doing what he always does.
    """
    form = splits.recent_form(frame, last_n=last_n)
    if not form["last_n"] or form["shifts"].empty:
        return None

    notable = form["shifts"][form["shifts"]["notable"]]
    parts = []
    for r in notable.itertuples():
        direction = "up" if r.delta > 0 else "down"
        parts.append(f"{name(r.pitch_type)} {direction} to {_pct(r.recent_share)} "
                     f"from {_pct(r.earlier_share)}")

    velo = form["velo_delta"]
    if velo == velo and abs(velo) >= 0.5 and form["fastball"]:
        direction = "up" if velo > 0 else "down"
        parts.append(f"{name(form['fastball'])} velocity {direction} "
                     f"{abs(velo):.1f} mph")

    if not parts:
        return None

    def short(date: str) -> str:
        stamp = pd.Timestamp(date)
        return f"{stamp.strftime('%b')} {stamp.day}"

    first, last = short(form["dates"][-1]), short(form["dates"][0])
    window = f"Last {form['last_n']} outings ({first} to {last}"

    # Postseason outings are a different setting — shorter rest, more relief,
    # more adrenaline — and a reader should know when "lately" means October.
    if "game_type" in frame.columns:
        recent_types = (
            frame[frame["game_date"].astype(str).str[:10].isin(form["dates"])]
            .drop_duplicates("game_pk")["game_type"]
        )
        post = int((recent_types != "R").sum())
        if post == len(recent_types) and post:
            window += ", all postseason"
        elif post:
            window += f", {post} postseason"
    window += ")"

    text = window + ": " + "; ".join(parts) + "."
    return _key("Lately", text, form["n_recent"])


def count_tell_key(frame: pd.DataFrame, min_lift: float | None = None) -> dict | None:
    """A pitch that jumps in specific counts to more than double his norm.

    3-0 is excluded. Nearly every pitcher throws a fastball 3-0, so a lift there
    describes the count, not the pitcher, and a coach already knows it.
    """
    if min_lift is None:
        min_lift = _cut("count_tell_lift", 2.0)
    min_n = int(config.get("flags.min_n.predictable_count", 20))
    lifts = counts.count_lifts(frame, min_n=min_n)
    if len(lifts) == 0:
        return None

    strong = lifts[(lifts["lift"] >= min_lift) & (lifts["count"] != "3-0")]
    if len(strong) == 0:
        return None

    pitch = strong.sort_values("score", ascending=False).iloc[0]["pitch_type"]
    rows = strong[strong["pitch_type"] == pitch].sort_values("count")
    which = " and ".join(rows["count"])
    peak = rows["share"].max()
    own = rows.iloc[0]["own_rate"]
    n = int(rows["n"].sum())

    text = (f"In {which} the {name(pitch)} jumps to about {_pct(peak)} — more "
            f"than double his normal {_pct(own)}. Expect it there.")
    return _key("Count tell", text, n)


def location_key(frame: pd.DataFrame) -> dict | None:
    """Where the ball is headed says which pitch it is, when that holds strongly."""
    min_n = int(config.get("flags.min_n.location_tell", 40))
    min_lift = float(config.get("flags.thresholds.location_tell_lift", 1.35))
    min_share = float(config.get("flags.thresholds.location_tell_share", 0.45))

    tells = location.location_tells(frame, by="v_band", min_n=min_n)
    if len(tells) == 0:
        return None
    strong = tells[(tells["lift"] >= min_lift) & (tells["p_pitch"] >= min_share)]
    if len(strong) == 0:
        return None

    top = strong.sort_values("score", ascending=False).iloc[0]
    # DOWN is the bottom third of his zone AND everything below it, so "down"
    # rather than "down in the zone".
    where = {"UP": "up in the zone", "DOWN": "down",
             "MIDDLE": "at the belt"}.get(top.band, top.band.lower())
    text = (f"If it's {where}, it's probably the {name(top.pitch_type)} "
            f"({_pct(top.p_pitch)} of pitches there).")
    return _key("Read the height", text, int(top.n))


def count_headline(frame: pd.DataFrame, min_lift: float = 1.25) -> str | None:
    """One sentence stating what the count grid shows, for its title.

    A chart title should state the finding, not name the metric. This finds the
    pitch that rises most in hitter's counts and the one that rises most with
    two strikes, and says so — adding that they stay out of each other's counts
    when that is also true. Returns None when neither rises enough to be worth
    a headline, and the chart gets a plain title instead.
    """
    regions = counts.count_region_lifts(frame)
    if len(regions) == 0:
        return None

    # A pitcher with no pitches in one region has no lift there. That must
    # leave the headline out, not raise — an earlier version crashed the whole
    # report on a pitcher who had never thrown a two-strike pitch in the
    # sample, which a short-season pitcher can genuinely produce.
    h_lifts = regions["hitter_lift"].dropna()
    t_lifts = regions["two_strike_lift"].dropna()
    if h_lifts.empty and t_lifts.empty:
        return None

    hitter = h_lifts.idxmax() if len(h_lifts) else None
    two = t_lifts.idxmax() if len(t_lifts) else None
    h_lift = float(h_lifts.max()) if len(h_lifts) else 0.0
    t_lift = float(t_lifts.max()) if len(t_lifts) else 0.0

    if h_lift < min_lift and t_lift < min_lift:
        return None
    if hitter is not None and hitter == two:
        return (f"The {name(hitter)} rises both in hitter's counts and with "
                f"two strikes.")

    parts = []
    if h_lift >= min_lift:
        parts.append(f"the {name(hitter)} comes out in hitter's counts")
    if t_lift >= min_lift:
        parts.append(f"the {name(two)} with two strikes")
    sentence = " and ".join(parts)
    sentence = sentence[0].upper() + sentence[1:]

    apart = (
        h_lift >= min_lift and t_lift >= min_lift
        and float(regions.loc[hitter, "two_strike_lift"]) < 0.8
        and float(regions.loc[two, "hitter_lift"]) < 0.8
    )
    if apart:
        sentence += ", and each rarely shows up in the other's counts"
    return sentence + "."


def platoon_headline(frame: pd.DataFrame, rare: float = 0.03) -> str | None:
    """One sentence stating what the platoon slope chart shows.

    Two kinds of split get named. A pitch one side almost never sees is the
    sharpest — it shrinks that side's problem — and a large usage gap on a pitch
    both sides do see. When the largest gap is big (15 points or more) it leads,
    because it changes the plan for every at-bat on one side; otherwise the
    never-see list leads and the biggest remaining gap follows.
    """
    usage = counts.restrict_to_arsenal(frame)
    if len(usage) == 0:
        return None

    shares = {
        side: usage[usage["stand"] == side]["pitch_type"].value_counts(normalize=True)
        for side in ("L", "R")
    }
    if any(len(s) == 0 for s in shares.values()):
        return None
    pitches = list(usage["pitch_type"].value_counts().index)

    def share(side: str, p: str) -> float:
        return float(shares[side].get(p, 0.0))

    unseen = {
        side: [p for p in pitches
               if share(side, p) < rare and share("R" if side == "L" else "L", p) >= rare]
        for side in ("L", "R")
    }
    gaps = sorted(
        ((p, share("L", p) - share("R", p)) for p in pitches
         if p not in unseen["L"] + unseen["R"]),
        key=lambda pair: -abs(pair[1]),
    )

    def gap_clause(p: str, g: float) -> str:
        more, less = ("lefties", "righties") if g > 0 else ("righties", "lefties")
        hi = share("L" if g > 0 else "R", p)
        lo = share("R" if g > 0 else "L", p)
        return f"{more} get the {name(p)} {_pct(hi)} of the time and {less} {_pct(lo)}"

    unseen_clauses = [
        f"{SIDE_NAMES[side]} almost never see the {' or the '.join(name(p) for p in ps)}"
        for side, ps in unseen.items() if ps
    ]

    if gaps and abs(gaps[0][1]) >= 0.15:
        text = gap_clause(*gaps[0])
        if unseen_clauses:
            text += ", and " + " and ".join(unseen_clauses)
    elif unseen_clauses:
        text = " and ".join(unseen_clauses)
        if gaps and abs(gaps[0][1]) >= 0.08:
            p, g = gaps[0]
            more = "L" if g > 0 else "R"
            if len([s for s in unseen if unseen[s]]) == 1 and unseen[more]:
                # Same side as the never-see clause: continue the sentence
                # rather than naming the side again.
                other = "R" if more == "L" else "L"
                text += (f", and get the {name(p)} more often "
                         f"({_pct(share(more, p))} to {_pct(share(other, p))} "
                         f"for {SIDE_NAMES[other]})")
            else:
                text += "; " + gap_clause(p, g)
    elif gaps and abs(gaps[0][1]) >= 0.08:
        text = gap_clause(*gaps[0])
    else:
        return "His mix barely changes with the hitter's side."

    return text[0].upper() + text[1:] + "."


def movement_headline(frame: pd.DataFrame, min_usage: float = 0.05) -> str | None:
    """One sentence on how his best swing-and-miss pitch moves against his fastball.

    Separation is what makes a secondary pitch hard to hit: the same arm speed
    with very different movement. So the headline compares his best whiff pitch
    (by whiffs per swing, among non-fastballs he uses at least `min_usage`) with
    his primary fastball — how much more it drops, how much more it runs, and
    how much slower it is. "Only N mph slower" is said only when the gap is
    small enough to be a reason the pitch works.

    It says nothing about whether the two look alike out of the hand. That is a
    tunneling claim, and nothing in this project measures it yet.
    """
    from src.metrics import arsenal

    table = arsenal.scout_arsenal(frame)
    profile = arsenal.profile(frame)
    fastball = splits.primary_fastball(counts.restrict_to_arsenal(frame))
    if len(table) == 0 or fastball not in table.index:
        return None

    candidates = table[
        (table["usage"] >= min_usage)
        & (~table.index.map(lambda p: PITCH_FAMILY.get(p) == "hard"))
    ].dropna(subset=["whiff_rate"])
    if len(candidates) == 0:
        return None

    best = candidates["whiff_rate"].idxmax()
    drop = float(table.loc[fastball, "ivb"] - table.loc[best, "ivb"])
    run = float(table.loc[best, "arm_run"] - table.loc[fastball, "arm_run"])
    slower = float(profile.loc[fastball, "velo"] - profile.loc[best, "velo"])

    moves = []
    if abs(drop) >= 4:
        moves.append(f"drops {abs(drop):.0f} inches {'more' if drop > 0 else 'less'}")
    if abs(run) >= 6:
        side = "his arm side" if run > 0 else "his glove side"
        moves.append(f"moves {abs(run):.0f} inches more to {side}")
    if not moves:
        return (f"The {name(best)} is his best swing-and-miss pitch "
                f"({_pct(table.loc[best, 'whiff_rate'])} of swings miss).")

    speed = (f" at only {slower:.0f} mph slower" if 0 < slower <= 6
             else f", {slower:.0f} mph slower")
    return (f"The {name(best)} is his best swing-and-miss pitch "
            f"({_pct(table.loc[best, 'whiff_rate'])} of swings miss): it "
            f"{' and '.join(moves)} than his {name(fastball)}{speed}.")


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------


def build(frame: pd.DataFrame, last_n: int = 5) -> dict:
    """The full hitting plan.

    Returns {"L": [...], "R": [...], "both": [...], "basis": str}, each list a
    sequence of {"label", "text", "n"} in the order a hitter would want them:
    first pitch, ahead in the count, two strikes, then what he won't see.
    """
    plan = {"L": [], "R": [], "both": [], "basis": ""}
    if len(frame) == 0:
        return plan

    usage = counts.situational_usage(frame)

    for side in ("L", "R"):
        for key in (
            first_pitch_key(frame, usage, side),
            hitters_count_key(usage, side),
            two_strike_key(frame, usage, side),
            wont_show_key(frame, side),
        ):
            if key:
                plan[side].append(key)

    for key in (
        recent_change_key(frame, last_n=last_n),
        count_tell_key(frame),
        location_key(frame),
    ):
        if key:
            plan["both"].append(key)

    plan["basis"] = (
        "Built from how often he does things, which is well measured at this "
        "sample. What those patterns cost him in runs is not resolved by one "
        "season, so the plan does not claim it."
    )
    return plan
